CONFIG_NAME: 'MirrorGAN'
DATASET_NAME: 'birds'
DATA_DIR: 'D:\\conda3\\Transfer_Learning\\GANDatasets\\birds'
GPU_ID: 0
WORKERS: 0
OUTPUT_PATH: 'D:\\conda3\\Transfer_Learning\\GANs\\text-to-image\\MirrorGAN-master\\outputs\\qtt'
TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: True
    NET_G: ''
    B_NET_D: True
    BATCH_SIZE: 4  # 22
    MAX_EPOCH: 650
    SNAPSHOT_INTERVAL: 50
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002

    NET_E: 'D:\\conda3\\Transfer_Learning\\GANs\\text-to-image\\MirrorGAN-master\\outputs\\stem\\text_encoder200.pth'
    SMOOTH:
        GAMMA1: 4.0  # 1,2,5 good 4 best  10&100bad
        GAMMA2: 5.0
        GAMMA3: 10.0  # 10good 1&100bad
        LAMBDA: 0.0
        LAMBDA1: 10.0

CAP:
    embed_size: 256
    hidden_size: 256
    num_layers: 1
    learning_rate: 0.001
    caption_cnn_path: 'D:\\conda3\\Transfer_Learning\\GANs\\text-to-image\\MirrorGAN-master\\outputs\\encoder-5-3000.ckpt'
    caption_rnn_path: 'D:\\conda3\\Transfer_Learning\\GANs\\text-to-image\\MirrorGAN-master\\outputs\\decoder-5-3000.ckpt'

GAN:
    DF_DIM: 64
    GF_DIM: 32
    Z_DIM: 100
    R_NUM: 2

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
