devices: (0,1,)
MODEL:
  LABEL: [
    "person","bicycle","car","motorbike","aeroplane","bus","train",
    "truck","boat","traffic light","fire hydrant","stop sign",
    "parking meter","bench","bird","cat","dog","horse","sheep",
    "cow","elephant","bear","zebra","giraffe","backpack","umbrella",
    "handbag","tie","suitcase","frisbee","skis","snowboard","sports ball",
    "kite","baseball bat","baseball glove","skateboard","surfboard",
    "tennis racket","bottle","wine glass","cup","fork","knife","spoon","bowl",
    "banana","apple","sandwich","orange","broccoli","carrot","hot dog","pizza","donut",
    "cake","chair","sofa","pottedplant","bed","diningtable","toilet","tvmonitor",
    "laptop","mouse","remote","keyboard","cell phone","microwave","oven",
    "toaster","sink","refrigerator","book", "clock","vase","scissors","teddy bear",
    "hair drier","toothbrush"
  ]
  numcls: 80
  modeltype: StrongerV3KL
  backbone: 'mobilenetv2'
  backbone_pretrained: 'checkpoints/mobilenet_v2.pth'
  boxloss: KL
  l1scale: 0.1
  clsfocal: True
  seprelu: False
  ASFF: True
EXPER:
  experiment_name: "coco512"
  train_sizes: [480, 512]
  test_size: 512

EVAL:
  varvote: True

DATASET:
  dataset: 'COCO'
  dataset_root: '/home/ff/myProject/KGT/myProjects/myDataset/coco'

OPTIM:
  batch_size: 4
  lr_initial: 2e-4
  total_epoch: 120
  milestones: [80,100]

Prune:
  sparse: False
