MODEL:
  LABEL: [
  "aeroplane",
  "bicycle",
  "bird",
  "boat",
  "bottle",
  "bus",
  "car",
  "cat",
  "chair",
  "cow",
  "diningtable",
  "dog",
  "horse",
  "motorbike",
  "person",
  "pottedplant",
  "sheep",
  "sofa",
  "train",
  "tvmonitor"
  ]
  numcls: 20
  modeltype: StrongerV3
  backbone: 'mobilenetv2'
  backbone_pretrained: 'checkpoints/mobilenet_v2.pth'
EXPER:
  experiment_name: 'strongerv3_sparse'
  resume: 'best'

DATASET:
  dataset: 'VOC'

OPTIM:
  batch_size: 12
  lr_initial: 2e-4
  total_epoch: 3
  milestones: [1,2]

Prune:
  sparse: True
  pruneratio: 0.3
  bbOutName: ('backbone.features.6','backbone.features.13','backbone.features.18')

finetune: True
devices: 1,