task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ff/myProject/KGT/myProjects/myDataset/coco/train2014/train2014
    ann_file: /home/ff/myProject/KGT/myProjects/myDataset/coco/captions/annotations/instances_train2014.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 8
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ff/myProject/KGT/myProjects/myDataset/coco/val2014/val2014
    ann_file: /home/ff/myProject/KGT/myProjects/myDataset/coco/captions/annotations/instances_val2014.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 8
  drop_last: False